from .autocomplete_fields_admin import AutocompleteFieldsAdminMixin
from .generic_foreign_key import GenericForeignKeyAdminMixin
from .generic_foreign_key_inline import GenericForeignKeyInlineAdminMixin
from .clickable_links_admin import ClickableLinksAdminMixin
from .autocomplete_changelist_filters_admin import (
    AutocompleteChangelistFiltersAdminMixin,
)
