# Generated by Django 2.2.1 on 2019-06-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foo',
            name='bar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.Bar'),
        ),
        migrations.AddField(
            model_name='foo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
