# Generated by Django 2.2.2 on 2019-07-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baz',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
