# Generated by Django 2.2.2 on 2019-07-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test_app', '0007_auto_20190723_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='link_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='link_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
